version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22  # node 22 environment
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-

      - run:
          name: install deps
          command: npm ci

      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: build svelte frontend
          command: npm run build

      - run:
          name: install flatpak
          command: |
            sudo apt-get update
            sudo apt-get install -y flatpak flatpak-builder

      - run:
          name: build electron app (linux)
          command: npx electron-builder --linux --publish never

      - persist_to_workspace:
          root: .
          paths:
            - dist

      - run:
          name: list artifacts
          command: ls -R dist

workflows:
  build_and_test:
    jobs:
      - build
