version: 2.1

jobs:
  build:
    docker:
      - image: node:22
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install deps
          command: npm ci

      - run:
          name: build svelte frontend
          command: npm run build

      - run:
          name: install flatpak
          command: |
            apt-get update
            apt-get install -y flatpak flatpak-builder

      - run:
          name: build electron app (linux)
          command: npx electron-builder --linux --publish never

      - store_artifacts:
          path: dist
          destination: electron-dist

      - run:
          name: list artifacts
          command: ls -R dist

workflows:
  build_and_store:
    jobs:
      - build
