name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write     

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node (or your build env)
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install deps & build
        run: |
          npm install
          npm run build
          npm run dist

      - name: Upload dist assets to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/**     
          file_glob: true
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
