name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Install libfuse2
        run: sudo apt-get install -y libfuse2
      - name: Build
        run: npm run dist
      - name: Get AppImage Artifact Path
        id: artifact_appimage
        run: echo "path=$(ls dist/Silverr*.AppImage)" >> $GITHUB_OUTPUT
      - name: Get RPM Artifact Path
        id: artifact_rpm
        run: echo "path=$(ls dist/Silverr*.rpm)" >> $GITHUB_OUTPUT
      - name: Get DEB Artifact Path
        id: artifact_deb
        run: echo "path=$(ls dist/Silverr*.deb)" >> $GITHUB_OUTPUT
      - name: Upload AppImage to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.artifact_appimage.outputs.path }}
          asset_name: ${{ steps.artifact_appimage.outputs.path }}
          asset_content_type: application/x-appimage
      - name: Upload RPM to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.artifact_rpm.outputs.path }}
          asset_name: ${{ steps.artifact_rpm.outputs.path }}
          asset_content_type: application/x-rpm
      - name: Upload DEB to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.artifact_deb.outputs.path }}
          asset_name: ${{ steps.artifact_deb.outputs.path }}
          asset_content_type: application/vnd.debian.binary-package
